### PR TITLE
feat(build image): update buildspec to work w/new pocket-build image

### PR DESCRIPTION
**Pull request by cmharlow**
## Goal

~Follows successful review, merge & deploy of https://github.com/Pocket/shared-infrastructure/pull/506 & https://github.com/Pocket/shared-infrastructure/pull/507~

Updates the repo's own Codebuild spec to work with the new pocket-build image, which doesn't require install steps (minus some uncertainty about perl-utils). Changes from alpine to ubuntu OS. This addresses multiple reports of Codebuild issues on the current (about to be replaced, unless you want to delay on changing) hashicorp/terraform image, which builds upon older versions of Alpine. If you want to opt out, just let me know here and I'll not change this repo's codebuild image in the upstream PRs.

~Blocked by [#507](https://github.com/Pocket/shared-infrastructure/pull/507) (which updates the codebuild project to use the new image which this buildspec will run on).~

## Reference

Tickets:
* https://getpocket.atlassian.net/browse/INFRA-847

[INFRA-847]: https://getpocket.atlassian.net/browse/INFRA-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mmiermans — COMMENTED** [review]
:heavy_check_mark: Looks good to me.

**Review by mmiermans — APPROVED** [review]

**Comment by braunreyes** [comment]
comment to see if I can get builds running.

**Comment by braunreyes** [comment]
these builds are not running...checking with @cmharlow if I can just include the new buildspec in my data-flows PR....I need it anyway to run checks on my code using the new image

**Comment by cmharlow** [comment]
@mmiermans @braunreyes can we merge this sometime this week? I don't see the commits pulled in elsewhere, and i'm trying to make sure all the necessary changes from the codebuild docker image work are merged before I close the overall ticket. Thanks!

**Comment by braunreyes** [comment]
I have the changes in another PR and should be merging that today.

-Braun

**Comment by cmharlow** [comment]
okay, just as a circleci hack for the future - when this situation happens, if you push up the same commits in a branch, the CI will pass here as well (circleci matches on commits).

So: 
```
git clone https://github.com/Pocket/data-flows
cd data-flows
git fetch origin pull/189/head:charlow_INFRA-847_buildspec
git checkout charlow_INFRA-847_buildspec
git push origin charlow_INFRA-847_buildspec
```

should result in a branch in the repo with those commits, and once the same commit anywhere is green in Circleci, the commits should be green in all branches/PRs with them. Cherrypicking these commits into your branch would've done that as well. Just a FYI for the future in case helpful. I can also wait for the different commits to go through the alternate PR, and thanks!

**Pull request closed without merging**
